version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # RabbitMQ main port
      - "15672:15672"    # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  user-service:
    build: ./services/user
    environment:
      RABBITMQ_URL: amqp://rabbitmq
    depends_on:
      - rabbitmq

  item-service:
    build: ./services/item
    environment:
      RABBITMQ_URL: amqp://rabbitmq
    depends_on:
      - rabbitmq

  order-service:
    build: ./services/order
    environment:
      RABBITMQ_URL: amqp://rabbitmq
    depends_on:
      - rabbitmq

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - item-service
      - order-service